/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Usuario
 */
public class FrmCategorias extends javax.swing.JFrame {

    /**
     * Creates new form FrmCategorias
     */
    public FrmCategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCategorias = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlFrutas = new javax.swing.JPanel();
        btnFrutas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlCarnes = new javax.swing.JPanel();
        btnCarnes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnlLacteos = new javax.swing.JPanel();
        btnLacteos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pnlRefrescos = new javax.swing.JPanel();
        btnRefrescos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pnlSnacks = new javax.swing.JPanel();
        btnSnacks = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pnlLicores = new javax.swing.JPanel();
        btnLicores = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pnlLimpieza = new javax.swing.JPanel();
        btnLimpieza = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pnlEnlatados = new javax.swing.JPanel();
        btnEnlatados = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlCategorias.setBackground(new java.awt.Color(255, 255, 255));

        pnlLogo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pnlFrutas.setBackground(new java.awt.Color(62, 184, 48));
        pnlFrutas.setPreferredSize(new java.awt.Dimension(307, 200));

        btnFrutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Frutas y Verduras.png"))); // NOI18N
        btnFrutas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnFrutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrutasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Frutas y Verduras");

        javax.swing.GroupLayout pnlFrutasLayout = new javax.swing.GroupLayout(pnlFrutas);
        pnlFrutas.setLayout(pnlFrutasLayout);
        pnlFrutasLayout.setHorizontalGroup(
            pnlFrutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFrutasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(74, 74, 74))
        );
        pnlFrutasLayout.setVerticalGroup(
            pnlFrutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFrutasLayout.createSequentialGroup()
                .addComponent(btnFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pnlCarnes.setBackground(new java.awt.Color(62, 184, 48));
        pnlCarnes.setPreferredSize(new java.awt.Dimension(307, 200));

        btnCarnes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Carnes.png"))); // NOI18N
        btnCarnes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCarnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarnesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Carnicería");

        javax.swing.GroupLayout pnlCarnesLayout = new javax.swing.GroupLayout(pnlCarnes);
        pnlCarnes.setLayout(pnlCarnesLayout);
        pnlCarnesLayout.setHorizontalGroup(
            pnlCarnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCarnes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlCarnesLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel3))
        );
        pnlCarnesLayout.setVerticalGroup(
            pnlCarnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarnesLayout.createSequentialGroup()
                .addComponent(btnCarnes, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlLacteos.setBackground(new java.awt.Color(62, 184, 48));
        pnlLacteos.setPreferredSize(new java.awt.Dimension(307, 200));

        btnLacteos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lacteos.png"))); // NOI18N
        btnLacteos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLacteos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLacteosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lácteos");

        javax.swing.GroupLayout pnlLacteosLayout = new javax.swing.GroupLayout(pnlLacteos);
        pnlLacteos.setLayout(pnlLacteosLayout);
        pnlLacteosLayout.setHorizontalGroup(
            pnlLacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLacteosLayout.createSequentialGroup()
                .addGroup(pnlLacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLacteos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlLacteosLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLacteosLayout.setVerticalGroup(
            pnlLacteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLacteosLayout.createSequentialGroup()
                .addComponent(btnLacteos, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pnlRefrescos.setBackground(new java.awt.Color(62, 184, 48));

        btnRefrescos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Refrescos jpg.png"))); // NOI18N
        btnRefrescos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRefrescos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Refrescos y Gaseosas");

        javax.swing.GroupLayout pnlRefrescosLayout = new javax.swing.GroupLayout(pnlRefrescos);
        pnlRefrescos.setLayout(pnlRefrescosLayout);
        pnlRefrescosLayout.setHorizontalGroup(
            pnlRefrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRefrescos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlRefrescosLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel5))
        );
        pnlRefrescosLayout.setVerticalGroup(
            pnlRefrescosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRefrescosLayout.createSequentialGroup()
                .addComponent(btnRefrescos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSnacks.setBackground(new java.awt.Color(62, 184, 48));

        btnSnacks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Snacks Menu.png"))); // NOI18N
        btnSnacks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSnacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSnacksActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Snacks y Golosinas");

        javax.swing.GroupLayout pnlSnacksLayout = new javax.swing.GroupLayout(pnlSnacks);
        pnlSnacks.setLayout(pnlSnacksLayout);
        pnlSnacksLayout.setHorizontalGroup(
            pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSnacksLayout.createSequentialGroup()
                .addComponent(btnSnacks, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlSnacksLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSnacksLayout.setVerticalGroup(
            pnlSnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSnacksLayout.createSequentialGroup()
                .addComponent(btnSnacks, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlLicores.setBackground(new java.awt.Color(62, 184, 48));

        btnLicores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Licores jpg.png"))); // NOI18N
        btnLicores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLicores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicoresActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Licores");

        javax.swing.GroupLayout pnlLicoresLayout = new javax.swing.GroupLayout(pnlLicores);
        pnlLicores.setLayout(pnlLicoresLayout);
        pnlLicoresLayout.setHorizontalGroup(
            pnlLicoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLicores, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlLicoresLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel7))
        );
        pnlLicoresLayout.setVerticalGroup(
            pnlLicoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLicoresLayout.createSequentialGroup()
                .addComponent(btnLicores, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        pnlLimpieza.setBackground(new java.awt.Color(62, 184, 48));

        btnLimpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpieza Menu.png"))); // NOI18N
        btnLimpieza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiezaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Limpieza");

        javax.swing.GroupLayout pnlLimpiezaLayout = new javax.swing.GroupLayout(pnlLimpieza);
        pnlLimpieza.setLayout(pnlLimpiezaLayout);
        pnlLimpiezaLayout.setHorizontalGroup(
            pnlLimpiezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLimpiezaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(111, 111, 111))
        );
        pnlLimpiezaLayout.setVerticalGroup(
            pnlLimpiezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLimpiezaLayout.createSequentialGroup()
                .addComponent(btnLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        pnlEnlatados.setBackground(new java.awt.Color(62, 184, 48));

        btnEnlatados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Enlatados.png"))); // NOI18N
        btnEnlatados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEnlatados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnlatadosActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enlatados");

        javax.swing.GroupLayout pnlEnlatadosLayout = new javax.swing.GroupLayout(pnlEnlatados);
        pnlEnlatados.setLayout(pnlEnlatadosLayout);
        pnlEnlatadosLayout.setHorizontalGroup(
            pnlEnlatadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEnlatados, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlEnlatadosLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel9))
        );
        pnlEnlatadosLayout.setVerticalGroup(
            pnlEnlatadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnlatadosLayout.createSequentialGroup()
                .addComponent(btnEnlatados, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlCategoriasLayout = new javax.swing.GroupLayout(pnlCategorias);
        pnlCategorias.setLayout(pnlCategoriasLayout);
        pnlCategoriasLayout.setHorizontalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                                .addComponent(pnlFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlSnacks, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlCarnes, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(pnlRefrescos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlLicores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlLacteos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                                .addComponent(pnlLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(pnlEnlatados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(179, 179, 179))))))
        );
        pnlCategoriasLayout.setVerticalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlCarnes, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(pnlFrutas, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(pnlLacteos, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRefrescos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSnacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLicores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLimpieza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEnlatados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCategorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFrutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrutasActionPerformed
        this.setVisible(false);
        FrmFrutas form = new FrmFrutas();
        form.setVisible(true);
    }//GEN-LAST:event_btnFrutasActionPerformed

    private void btnCarnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarnesActionPerformed
         this.setVisible(false);
        FrmCarniceria form = new FrmCarniceria();
        form.setVisible(true);
    }//GEN-LAST:event_btnCarnesActionPerformed

    private void btnLacteosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLacteosActionPerformed
         this.setVisible(false);
        FrmLacteos form = new FrmLacteos();
        form.setVisible(true);
    }//GEN-LAST:event_btnLacteosActionPerformed

    private void btnRefrescosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescosActionPerformed
         this.setVisible(false);
        FrmRefrescos form = new FrmRefrescos();
        form.setVisible(true);
    }//GEN-LAST:event_btnRefrescosActionPerformed

    private void btnSnacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSnacksActionPerformed
         this.setVisible(false);
        FrmSnacks form = new FrmSnacks();
        form.setVisible(true);
    }//GEN-LAST:event_btnSnacksActionPerformed

    private void btnLicoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicoresActionPerformed
         this.setVisible(false);
        FrmLicores form = new FrmLicores();
        form.setVisible(true);
    }//GEN-LAST:event_btnLicoresActionPerformed

    private void btnLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiezaActionPerformed
         this.setVisible(false);
        FrmLimpieza form = new FrmLimpieza();
        form.setVisible(true);
    }//GEN-LAST:event_btnLimpiezaActionPerformed

    private void btnEnlatadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnlatadosActionPerformed
         this.setVisible(false);
        FrmEnlatados form = new FrmEnlatados();
        form.setVisible(true);
    }//GEN-LAST:event_btnEnlatadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarnes;
    private javax.swing.JButton btnEnlatados;
    private javax.swing.JButton btnFrutas;
    private javax.swing.JButton btnLacteos;
    private javax.swing.JButton btnLicores;
    private javax.swing.JButton btnLimpieza;
    private javax.swing.JButton btnRefrescos;
    private javax.swing.JButton btnSnacks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlCarnes;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JPanel pnlEnlatados;
    private javax.swing.JPanel pnlFrutas;
    private javax.swing.JPanel pnlLacteos;
    private javax.swing.JPanel pnlLicores;
    private javax.swing.JPanel pnlLimpieza;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlRefrescos;
    private javax.swing.JPanel pnlSnacks;
    // End of variables declaration//GEN-END:variables
}
